app: Inkscape
binpatch: true

ingredients:
  packages:
    - inkscape
    - python-lxml
    - python-numpy
    - python-scour
  dist: trusty
  sources:
    - deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe
  ppas:
    - inkscape.dev/stable

script:
  - sed -i -e 's|Drawing Shortcut Group|X-Drawing Shortcut Group|g' inkscape.desktop
  - ls ../inkscape_*.deb | cut -d "_" -f 2 | cut -d "~" -f 1 | head -n 1 > ../VERSION
